### ISSUE TITLE
Images not shown?

### ISSUE THREAD

**Issue by Roelofpieter** [ranfdev/Geopard#13]
Hi there. Thanks for this fine piece of software. Just discovered Gemini and Geopard makes it a fine experience. I have installed it through flatpak (from https://flathub.org/apps/details/com.ranfdev.Geopard) on Fedora (36) and noticed that images aren't shown. When clinking an image-link the screen blanks and a "load bar" will show at the top of the view, but no matter how long I wait, no image is shown. I am not really sure if this is a bug, a problem with the flatpak or just not implemented yet. I'd thought I'd let you know. I have tried it amongst others with the image links on: gemini://caolan.uk/workshop/2020-10-25_bramley_buttons.gmi

regards,
Rolf

**Comment by ranfdev** [comment]
Thank you for the report.

Images are handled as any other binary file: they get downloaded and then you can open them with any program you want.
In Geopard 1.0.0 there was an error with the handling of binary files, the one you are mentioning. See #9.

This issue is fixed on the latest version, so I suggest you update Geopard.
